const FRAME_RATE = 10;
const GRID_SIZE = 20;
const CANVAS_HEIGHT = 900;
const CANVAS_WIDTH = 600;
const BULLET_DAMAGE = 10;
const BULLET_VELO = 3;
const TANK_LENGHT = 70;
const TANK_WIDTH = 70; 
const BULLET_WIDTH = 10;
const BULLET_LENGHT = 20;
const RADIUS_REDUC = 1;

module.exports = {
  FRAME_RATE,
  GRID_SIZE,
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  BULLET_DAMAGE,
  BULLET_VELO,
  TANK_LENGHT,
  TANK_WIDTH,
  BULLET_WIDTH,
  BULLET_LENGHT,
  RADIUS_REDUC
}
